// SPDX-License-Identifier: AGPL-3.0-or-later

//! Shared UI components — no server-side dependencies.

pub mod action_status;
pub mod attachment_extension;
pub mod attachment_hooks;
pub mod attribution;
pub mod avatar;
pub mod layout;
pub mod alert;
pub mod badge;
pub mod button;
pub mod card;
pub mod checkbox;
pub mod command_palette;
pub mod confirm_dialog;
pub mod date_picker;
pub mod dropdown;
pub mod empty_state;
pub mod input;
pub mod issue_status_badge;
pub mod label;
pub mod label_badge;
pub mod lightbox;
pub mod modal;
pub mod navigation_progress;
pub mod popover;
pub mod priority_indicator;
pub mod search_input;
pub mod select;
pub mod skeleton;
pub mod spinner;
pub mod status_badge;
pub mod switch;
pub mod team_icon;
pub mod team_icon_picker;
pub mod theme;
pub mod toast;
pub mod tooltip;

pub use action_status::ActionStatus;
pub use attachment_hooks::LightboxState;
pub use alert::{Alert, AlertDescription, AlertTitle, AlertVariant};
pub use avatar::{Avatar, AvatarSize};
pub use badge::{Badge, BadgeVariant};
pub use button::{Button, ButtonLink, ButtonSize, ButtonVariant, ToggleButton};
pub use card::{Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle};
pub use command_palette::{CommandPalette, CreateIssueTrigger};
pub use checkbox::Checkbox;
pub use confirm_dialog::ConfirmDialog;
pub use date_picker::DatePicker;
pub use dropdown::{DropdownItem, DropdownMenu, DropdownTrigger, Select, SelectVariant};
pub use empty_state::{EmptyState, EmptyStateVariant};
pub use input::INPUT_CLASS;
pub use issue_status_badge::{IssueStatusBadge, IssueStatusVariant};
pub use label::Label;
pub use label_badge::LabelBadge;
pub use lightbox::Lightbox;
pub use modal::{Modal, ModalSize};
pub use navigation_progress::NavigationProgress;
pub use priority_indicator::PriorityIndicator;
pub use search_input::SearchInput;
pub use select::{DynSelect, StyledSelect};
pub use skeleton::{Skeleton, SettingsPageSkeleton};
pub use spinner::Spinner;
pub use status_badge::{StatusBadge, StatusBadgeVariant};
pub use switch::Switch;
pub use team_icon::TeamIcon;
pub use team_icon_picker::TeamIconPicker;
pub use theme::ThemeProvider;
pub use tooltip::Tooltip;
