apiVersion: v1
kind: Secret
metadata:
  name: trakkt-secrets
  namespace: trakkt
type: Opaque
stringData:
  jwt-secret-key: "A2iJ+NnlRZHtRydxXD6RdorG4TshmN8dbOI0kNyhdP0="
  encryption-key: "1TbuRUeOTvHk5+ze2qq405l0SizJtQ38v+7H8ojAivw="
  db-password: "ewF3bzkFDsILxMCD4Xg8"
  db-user: "trakkt"
