apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: trakkt
  namespace: trakkt
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`app.trakkt.io`)
      services:
        - name: trakkt
          port: 80
