[package]
name = "trakkt-api"
version = "0.1.0"
edition = "2024"

[dependencies]
trakkt-core = { workspace = true }
trakkt-auth = { workspace = true }
trakkt-types = { workspace = true }
axum = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
