#!/usr/bin/env python3
# check-tx-pool.py — guards against touching the connection pool while a
# database transaction is open.
#
# Why this exists: crates/trakkt-core/src/db.rs pins the SQLite pool to
# `max_connections(1)`. A `DbTx` holds that single connection for its whole
# lifetime, so any pool acquisition issued before the transaction ends waits on
# a connection that cannot be released until it does. The request stalls until
# sqlx's 30s `acquire_timeout` fires and then fails with `PoolTimedOut`. Nothing
# else catches this: it compiles, clippy passes, and it only appears at runtime
# under whichever code path happens to take the wrong branch.
#
# The type system does not prevent it. `db: &DbPool` stays in scope for the
# whole function body after `db.begin()`, so `db` and `tx` are both usable at
# once and reaching for the wrong one is a plain typo. There are 54 transaction
# spans in crates/trakkt-auth/src today, all hand-verified clean during the
# TRA-9923 -> TRA-9954 conversion series; this check is what keeps them that way.
#
# The indirect case is not hypothetical. `broadcast_raw_to_workspace`
# (crates/trakkt-auth/src/websocket/manager.rs) queries the pool to resolve
# workspace members, which is why "commit before delivering" is a correctness
# requirement in this codebase rather than a style preference.
#
# ---------------------------------------------------------------------------
# What it checks
# ---------------------------------------------------------------------------
#
# Two kinds of region are treated as "a transaction is open here":
#
#   1. A span, from `let [mut] NAME = <expr>.begin().await` to the point NAME is
#      consumed (see "How span ends are decided" below).
#   2. The entire body of a function whose signature takes `&mut DbTx`. Such a
#      function can only be reached from inside a span, by construction — a
#      `&mut DbTx` is only obtainable from an owned, open `DbTx`.
#
# Inside either region, two things are violations:
#
#   1. Direct — a pool-scoped query macro. The macro list is read out of
#      crates/trakkt-core/src/db.rs: any `macro_rules!` whose body mentions
#      `DbPool::` is pool-scoped. Not hardcoded, so a new `db_*` macro is
#      covered the day it is written.
#   2. Indirect — a call to a function whose own signature takes `&DbPool`.
#      That set is discovered by scanning the crate's `fn` signatures, for the
#      same reason: a hand-maintained list of "dangerous helpers" is the same
#      defect one level up.
#
# Because rule 2 covers `&mut DbTx` helpers as regions in their own right, a
# `&mut DbTx` helper that calls a `&DbPool` helper IS caught, and so is any
# chain of them within a crate — the analysis reaches a fixpoint over
# intra-crate `&mut DbTx` calls.
#
# ---------------------------------------------------------------------------
# What it genuinely cannot see — these are gaps, not covered cases
# ---------------------------------------------------------------------------
#
#   * Anything crossing a crate boundary. A call inside a span to a `&DbPool`
#     function defined in a different crate is invisible: the callee set is
#     built per crate, deliberately, because matching by bare name across the
#     workspace would flag unrelated same-named functions.
#   * A helper that reaches the pool without naming it in its signature —
#     holding it in a struct field (`self.db`), behind a trait object, or
#     captured in a closure defined elsewhere. Only `&DbPool` parameters and
#     `&mut DbTx` parameters are visible to this check.
#   * Pool access generated by a macro other than the ones in db.rs, or by a
#     proc macro, since only the invocation site is text here.
#   * Anything reached through dynamic dispatch or a function pointer.
#   * A closure that is defined outside a span and called inside it — the
#     closure body is not analysed as part of the region.
#   * A second `db.begin()` on the same pool while a span is already open.
#     `DbPool::begin` takes `&self`, not an explicit `&DbPool` parameter, so it
#     is not in the callee set this check builds. Nesting a transaction inside
#     another on SQLite self-deadlocks for the same reason a pool call does.
#     No such pattern exists in the tree today (checked across all spans), but
#     it would not be caught if one were added.
#
# It is a textual analysis over comment- and string-stripped source. It does not
# type-check, so it matches callees by name within a crate.
#
# ---------------------------------------------------------------------------
# How span ends are decided
# ---------------------------------------------------------------------------
#
# A span is NOT "begin() to the next commit()". Transactions here end in several
# ways: `tx.commit()`, `tx.rollback()`, being moved into a consuming helper
# (`commit_and_deliver(tx, ...)`, `commit_team_update(tx, ...)`), or simply
# being dropped — which rolls back — when `?` propagates or the block ends.
#
# So the span is tracked by the liveness of the binding, brace-depth aware:
#
#   * The region starts at the `begin()` statement and ends where the block
#     holding the binding closes.
#   * `NAME` moved (used as a bare value, or `.commit()`/`.rollback()`) ends
#     liveness. `&NAME`, `&mut NAME`, `&mut *NAME` and other method calls
#     (`NAME.is_postgres()`) are borrows and do not.
#   * A move at the binding's own brace depth ends the span there: the pool is
#     free from that point on, which is exactly what makes post-commit
#     broadcasts legal.
#   * A move inside a nested block (an early-out branch) ends liveness only for
#     the rest of that block. Liveness resumes when the block closes, because
#     the path that skipped the branch still holds an open transaction.
#
# That last rule is only sound if the branch diverges — if control could fall
# out of the branch after the move, the transaction is closed on that path and
# open on the other, and one span end does not describe both. The check does not
# guess: it requires a `return`, `break` or `continue` after the move inside the
# same block, and hard-errors if there is none. Same for a `.begin()` that is
# not a plain `let` binding, and for a file whose braces do not balance. A check
# that quietly stops analysing part of the tree is worse than no check, so every
# construct it cannot model is a failure, not a skip.
#
# Run it locally before pushing:  scripts/check-tx-pool.py
#
# `--self-test` runs it against the fixtures in scripts/tests/tx-pool instead of
# the workspace. Run that after changing this script: the guard's own failure
# mode is silence, and a clean tree cannot tell you it still works.

import re
import sys
from itertools import accumulate
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# The file the pool-scoped macros are defined in. Also the file that documents
# the invariant this check enforces (see the `DbTx` doc comment there).
DB_RS = REPO_ROOT / "crates" / "trakkt-core" / "src" / "db.rs"

# Every workspace crate and binary. Transaction spans live in trakkt-auth today;
# scanning wider costs nothing and means a span added elsewhere is guarded from
# the moment it is written rather than from the moment someone remembers to
# widen this list.
SOURCE_GLOBS = ("crates/*/src/**/*.rs", "apps/*/src/**/*.rs")


class Failure(Exception):
    """A construct the analysis cannot model. Always fatal."""


def rel(path: Path) -> str:
    """Repo-relative path, so error output is uniform and clickable in CI."""
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


# ---------------------------------------------------------------------------
# Lexing: blank out comments and literals
# ---------------------------------------------------------------------------
#
# Required for correctness, not tidiness. Rust format strings contain braces
# ("UPDATE teams SET settings = {json_cast} ..."), which would corrupt the brace
# depth the span walk depends on, and comments in this codebase quote both
# `.begin()` and the `db_*` macro names when explaining precisely this rule.
#
# Returns a string of the same length with comment and literal *interiors*
# replaced by spaces, so every offset and line number still lines up with the
# original file.
def strip_noncode(src: str) -> str:
    out = list(src)
    i, n = 0, len(src)

    def blank(start: int, end: int) -> None:
        for k in range(start, end):
            if out[k] != "\n":
                out[k] = " "

    while i < n:
        c = src[i]

        if c == "/" and i + 1 < n and src[i + 1] == "/":
            j = src.find("\n", i)
            j = n if j == -1 else j
            blank(i, j)
            i = j
            continue

        if c == "/" and i + 1 < n and src[i + 1] == "*":
            # Rust block comments nest.
            depth, j = 1, i + 2
            while j < n and depth:
                if src.startswith("/*", j):
                    depth += 1
                    j += 2
                elif src.startswith("*/", j):
                    depth -= 1
                    j += 2
                else:
                    j += 1
            if depth:
                raise Failure("unterminated block comment")
            blank(i, j)
            i = j
            continue

        # Raw string: r"...", r#"..."#, br##"..."##
        m = re.compile(r'(?:b?r)(#*)"').match(src, i)
        if m and (i == 0 or not (src[i - 1].isalnum() or src[i - 1] == "_")):
            hashes = m.group(1)
            close = '"' + hashes
            j = src.find(close, m.end())
            if j == -1:
                raise Failure("unterminated raw string literal")
            blank(m.end(), j)
            i = j + len(close)
            continue

        if c == '"':
            j = i + 1
            while j < n:
                if src[j] == "\\":
                    j += 2
                    continue
                if src[j] == '"':
                    break
                j += 1
            if j >= n:
                raise Failure("unterminated string literal")
            blank(i + 1, j)
            i = j + 1
            continue

        # A quote is a char literal only when it closes; otherwise it is a
        # lifetime ('a, 'static) and must be left alone.
        if c == "'":
            m = re.compile(r"'(?:\\.[^']*|[^'\\])'").match(src, i)
            if m:
                blank(i + 1, m.end() - 1)
                i = m.end()
                continue
            i += 1
            continue

        i += 1

    return "".join(out)


def brace_depths(code: str) -> list[int]:
    """Depth *after* each character. depths[k-1] is the depth before offset k."""
    return list(accumulate(1 if c == "{" else -1 if c == "}" else 0 for c in code))


def depth_before(depths: list[int], off: int) -> int:
    return depths[off - 1] if off else 0


def line_of(line_starts: list[int], off: int) -> int:
    lo, hi = 0, len(line_starts) - 1
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if line_starts[mid] <= off:
            lo = mid
        else:
            hi = mid - 1
    return lo + 1


# ---------------------------------------------------------------------------
# Discovery: what counts as a pool access
# ---------------------------------------------------------------------------
def discover_pool_macros(db_rs_code: str) -> list[str]:
    """`macro_rules!` in db.rs whose body dispatches on `DbPool::`."""
    names = []
    for m in re.finditer(r"\bmacro_rules!\s+(\w+)\s*\{", db_rs_code):
        start = m.end() - 1
        depth, j = 0, start
        while j < len(db_rs_code):
            if db_rs_code[j] == "{":
                depth += 1
            elif db_rs_code[j] == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        else:
            raise Failure(
                f"{rel(DB_RS)}: unterminated macro_rules! body for {m.group(1)}"
            )
        if "DbPool::" in db_rs_code[start : j + 1]:
            names.append(m.group(1))
    return sorted(names)


FN_HEAD_RE = re.compile(r"\bfn\s+(\w+)")

POOL_PARAM_RE = re.compile(r"&\s*(?:[\w]+\s*::\s*)*DbPool\b")
TX_PARAM_RE = re.compile(r"&\s*mut\s+(?:[\w]+\s*::\s*)*DbTx\b")


def params_open(code: str, after_name: int, name: str, path: Path) -> int:
    """Offset of the `(` opening a fn's parameter list, skipping any generics.

    Generic lists nest (`<F: Future<Output = ()>>`) and can contain `->`, so
    this counts angle brackets rather than pattern-matching them. Getting this
    wrong would silently drop a signature from the `&DbPool` set — a check that
    cannot see a function is worse than one that flags it — so a head it cannot
    parse is a failure, not a skip.
    """
    n = len(code)
    j = after_name
    while j < n and code[j].isspace():
        j += 1

    if j < n and code[j] == "<":
        depth = 0
        while j < n:
            ch = code[j]
            if ch == "<":
                depth += 1
            elif ch == ">":
                depth -= 1
                if depth == 0:
                    j += 1
                    break
            elif ch == "-" and j + 1 < n and code[j + 1] == ">":
                j += 1  # the `>` of a `->` return type inside a bound
            j += 1
        else:
            raise Failure(f"{rel(path)}: unterminated generic list on `fn {name}`")
        while j < n and code[j].isspace():
            j += 1

    if j >= n or code[j] != "(":
        raise Failure(
            f"{rel(path)}: cannot locate the parameter list of `fn {name}` — this "
            f"check reads `&DbPool` and `&mut DbTx` parameters out of signatures and "
            f"will not silently skip one it failed to parse."
        )
    return j


def parse_fns(code: str, path: Path):
    """Yield (name, params_text, body_start, body_end) for each fn with a body."""
    for m in FN_HEAD_RE.finditer(code):
        open_paren = params_open(code, m.end(), m.group(1), path)
        # Balanced parameter list.
        depth, j = 0, open_paren
        while j < len(code):
            if code[j] == "(":
                depth += 1
            elif code[j] == ")":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        else:
            raise Failure(f"{rel(path)}: unterminated parameter list for fn {m.group(1)}")
        params = code[open_paren + 1 : j]

        # Body opens at the first `{` after the return type; a `;` first means a
        # trait method declaration with no body.
        k = j + 1
        while k < len(code) and code[k] not in "{;":
            k += 1
        if k >= len(code) or code[k] == ";":
            yield m.group(1), params, None, None
            continue

        depth, e = 0, k
        while e < len(code):
            if code[e] == "{":
                depth += 1
            elif code[e] == "}":
                depth -= 1
                if depth == 0:
                    break
            e += 1
        else:
            raise Failure(f"{rel(path)}: unterminated body for fn {m.group(1)}")
        yield m.group(1), params, k + 1, e


# ---------------------------------------------------------------------------
# Region analysis
# ---------------------------------------------------------------------------
STMT_BOUNDARY = re.compile(r"[;{}]")
LET_BINDING = re.compile(r"^\s*let\s+(?:mut\s+)?(\w+)\s*(?::[^=]*)?=")
DIVERGES = re.compile(r"\b(?:return|break|continue)\b")


def find_spans(code: str, depths: list[int], path: Path):
    """Yield (name, region_start, region_end, begin_depth) for each transaction."""
    for m in re.finditer(r"\.\s*begin\s*\(\s*\)", code):
        # Walk back to the previous statement boundary to find the binding.
        boundaries = [b.end() for b in STMT_BOUNDARY.finditer(code, 0, m.start())]
        stmt_start = boundaries[-1] if boundaries else 0
        binding = LET_BINDING.match(code[stmt_start : m.start()])
        if not binding:
            raise Failure(
                f"{rel(path)}: `.begin()` that is not a plain `let` binding — this check "
                f"cannot tell where the transaction ends, so it will not pretend to. "
                f"Bind it with `let mut tx = ...begin().await` or teach this script "
                f"the new shape."
            )
        name = binding.group(1)
        begin_depth = depth_before(depths, stmt_start)

        # The enclosing block runs until depth drops below begin_depth.
        end = None
        for off in range(m.end(), len(code)):
            if code[off] == "}" and depths[off] < begin_depth:
                end = off
                break
        if end is None:
            if begin_depth == 0:
                raise Failure(f"{rel(path)}: `.begin()` at brace depth 0 — unparseable")
            end = len(code)
        yield name, m.end(), end, begin_depth


def classify_binding_use(code: str, m: re.Match) -> str:
    """'move' if the binding is consumed here, 'borrow' otherwise."""
    tail = code[m.end() : m.end() + 32].lstrip()
    if tail.startswith("."):
        method = re.match(r"\.\s*(\w+)", tail)
        if method and method.group(1) in ("commit", "rollback"):
            return "move"
        return "borrow"
    head = code[max(0, m.start() - 16) : m.start()]
    if re.search(r"(?:&\s*mut\s+|&\s*|\*\s*)$", head):
        return "borrow"
    return "move"


def scan_region(code, depths, line_starts, path, start, end, checks, live_from_start,
                binding=None, begin_depth=0):
    """Report (line, kind, description) for violations while the transaction is open.

    `binding` is None for a `&mut DbTx` helper body, which is open throughout and
    has no binding to track; spans pass the binding name and its brace depth.
    """
    findings = []
    events = []

    for kind, rx, describe in checks:
        for m in rx.finditer(code, start, end):
            events.append((m.start(), 0, kind, describe(m)))

    if binding is not None:
        use_re = re.compile(r"\b" + re.escape(binding) + r"\b")
        for m in use_re.finditer(code, start, end):
            if classify_binding_use(code, m) == "move":
                events.append((m.start(), 1, "move", m))

    events.sort(key=lambda e: (e[0], e[1]))

    live = live_from_start
    revive_depth = None

    for off, _, kind, payload in events:
        d = depth_before(depths, off)
        if revive_depth is not None and d < revive_depth:
            live = True
            revive_depth = None

        if kind == "move":
            if d <= begin_depth:
                # Ends the span: the pool is free for the rest of the block.
                live = False
                revive_depth = None
            else:
                # An early-out branch. Sound only if control cannot fall out of
                # the branch with the transaction closed on one path and open on
                # the other, so require the branch to diverge.
                block_end = next(
                    (k for k in range(payload.end(), end) if code[k] == "}" and depths[k] < d),
                    end,
                )
                if not DIVERGES.search(code, payload.end(), block_end):
                    raise Failure(
                        f"{rel(path)}:{line_of(line_starts, off)}: `{binding}` is consumed "
                        f"inside a nested block that does not `return`, `break` or "
                        f"`continue`. The transaction is then closed on one path and "
                        f"open on the other and this check cannot say which applies to "
                        f"the code below. Restructure so the branch diverges, or hoist "
                        f"the consume to the binding's own scope."
                    )
                live = False
                revive_depth = d
            continue

        if live:
            findings.append((line_of(line_starts, off), kind, payload))

    return findings


# ---------------------------------------------------------------------------
def crate_of(path: Path) -> str:
    parts = path.relative_to(REPO_ROOT).parts
    return f"{parts[0]}/{parts[1]}"


def analyze(files: list[Path], pool_macros: list[str]):
    """Run both region analyses over `files`.

    Returns (findings, spans_checked, tx_fns_checked, pool_fns). Raises `Failure`
    for anything it cannot model. Shared by the real run and `--self-test` so the
    self-test exercises the same code path the guard runs in CI.
    """
    # Pass 1: strip every file once, and collect per-crate signatures.
    parsed = {}
    pool_fns: dict[str, dict[str, str]] = {}
    for path in files:
        code = strip_noncode(path.read_text())
        depths = brace_depths(code)
        if depths and depths[-1] != 0:
            raise Failure(f"{rel(path)}: braces do not balance (ends at depth {depths[-1]})")
        starts = [0] + [m.end() for m in re.finditer("\n", code)]
        parsed[path] = (code, depths, starts)

        crate = crate_of(path)
        for name, params, body_start, _ in parse_fns(code, path):
            if body_start is not None and POOL_PARAM_RE.search(params):
                pool_fns.setdefault(crate, {})[name] = rel(path)

    macro_rx = re.compile(r"\b(" + "|".join(map(re.escape, pool_macros)) + r")\s*!")

    findings = []
    spans_checked = 0
    tx_fns_checked = 0

    for path in files:
        code, depths, starts = parsed[path]
        crate = crate_of(path)
        relpath = rel(path)

        checks = [("macro", macro_rx, lambda m: f"pool-scoped macro `{m.group(1)}!`")]
        names = sorted(pool_fns.get(crate, {}))
        if names:
            fn_rx = re.compile(
                r"(?<![\w.])(" + "|".join(map(re.escape, names)) + r")\s*\("
            )
            defs = pool_fns[crate]
            checks.append((
                "fn",
                fn_rx,
                lambda m, defs=defs: f"call to `{m.group(1)}()`, which takes `&DbPool` "
                          f"({defs[m.group(1)]})",
            ))

        # Regions of kind 1: transaction spans.
        for binding, start, end, begin_depth in find_spans(code, depths, path):
            spans_checked += 1
            for line, kind, desc in scan_region(
                code, depths, starts, path, start, end, checks,
                live_from_start=True, binding=binding, begin_depth=begin_depth,
            ):
                findings.append((relpath, line, kind, desc,
                                 f"inside the transaction `{binding}` opened at "
                                 f"{relpath}:{line_of(starts, start)}"))

        # Regions of kind 2: bodies of `&mut DbTx` helpers.
        for name, params, body_start, body_end in parse_fns(code, path):
            if body_start is None or not TX_PARAM_RE.search(params):
                continue
            tx_fns_checked += 1
            for line, kind, desc in scan_region(
                code, depths, starts, path, body_start, body_end, checks,
                live_from_start=True,
            ):
                findings.append((relpath, line, kind, desc,
                                 f"inside `{name}()`, which takes `&mut DbTx` and "
                                 f"is therefore only reachable with a transaction "
                                 f"open"))

    return findings, spans_checked, tx_fns_checked, pool_fns


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------
#
# This guard can fail silently. A bug in span detection or in the signature
# parser makes it report nothing, which is indistinguishable from success when
# it runs against a tree that is already clean. Two such bugs existed while it
# was being written — a generic `fn` head the parser skipped, and a shadowed
# name that broke only the error paths — and neither was visible from the real
# run. The fixtures are what make the failure modes observable.
FIXTURE_DIR = REPO_ROOT / "scripts" / "tests" / "tx-pool"

EXPECT_RE = re.compile(r"^//\s*expect:\s*(.+?)\s*$", re.MULTILINE)


def self_test() -> int:
    fixtures = sorted(FIXTURE_DIR.glob("*.rs.txt"))
    if not fixtures:
        print(f"::error::No fixtures in {rel(FIXTURE_DIR)} — the self-test would pass "
              f"vacuously, which is the exact failure it exists to detect.")
        return 1

    try:
        pool_macros = discover_pool_macros(strip_noncode(DB_RS.read_text()))
    except (Failure, OSError) as e:
        print(f"::error::self-test cannot read the macro list from {rel(DB_RS)}: {e}")
        return 1

    failed = 0
    for fx in fixtures:
        directive = EXPECT_RE.search(fx.read_text())
        if not directive:
            print(f"::error::{rel(fx)} has no `// expect:` directive.")
            failed += 1
            continue
        expect = directive.group(1)

        error = None
        findings = []
        try:
            findings, _, _, _ = analyze([fx], pool_macros)
        except Failure as e:
            error = str(e)

        lines = sorted(f[1] for f in findings)

        if expect == "clean":
            ok = error is None and not lines
            got = f"error: {error}" if error else f"violations on {lines}"
        elif expect == "violations":
            # Marked inline, so editing a fixture's comments cannot silently
            # invalidate the expectation the way a header line list would.
            want = sorted(
                n for n, text in enumerate(fx.read_text().splitlines(), 1)
                if "//~ VIOLATION" in text
            )
            if not want:
                print(f"::error::{rel(fx)} expects violations but marks none "
                      f"with `//~ VIOLATION`.")
                failed += 1
                continue
            ok = error is None and lines == want
            got = f"error: {error}" if error else f"violations on {lines}, expected {want}"
        elif expect.startswith("error:"):
            want = expect.split(":", 1)[1]
            ok = error is not None and want in error
            got = f"error: {error}" if error else f"no error; violations on {lines}"
        else:
            print(f"::error::{rel(fx)}: unrecognised directive `{expect}`")
            failed += 1
            continue

        if ok:
            print(f"  ok    {fx.name}  ({expect})")
        else:
            failed += 1
            print(f"  FAIL  {fx.name}")
            print(f"        expected: {expect}")
            print(f"        actual:   {got}")

    if failed:
        print()
        print(f"::error::check-tx-pool self-test: {failed} of {len(fixtures)} fixtures "
              f"failed. The guard itself is broken — fix it before trusting a green run.")
        return 1

    print(f"✅ check-tx-pool self-test: {len(fixtures)} fixtures pass.")
    return 0


def main() -> int:
    if "--self-test" in sys.argv[1:]:
        return self_test()

    if not DB_RS.is_file():
        print(f"::error::{rel(DB_RS)} not found — this check reads the pool-scoped "
              f"macro list from it and cannot run without it.")
        return 1

    try:
        db_rs_code = strip_noncode(DB_RS.read_text())
        pool_macros = discover_pool_macros(db_rs_code)
    except Failure as e:
        print(f"::error::{e}")
        return 1

    if not pool_macros:
        print(f"::error::No pool-scoped macros found in {rel(DB_RS)}. Either they "
              f"moved or this check's discovery is broken; both are failures.")
        return 1

    files = sorted({p for g in SOURCE_GLOBS for p in REPO_ROOT.glob(g)})
    if not files:
        print("::error::No Rust sources matched — this check cannot guard files it "
              "cannot see.")
        return 1

    try:
        findings, spans_checked, tx_fns_checked, pool_fns = analyze(files, pool_macros)
    except Failure as e:
        print(f"::error::{e}")
        return 1

    if not any(pool_fns.values()):
        print("::error::No `&DbPool`-taking functions found in any crate. The indirect "
              "half of this check would be inert; that is a failure, not a pass.")
        return 1

    # A guard whose subject has disappeared is not passing, it is inert.
    if spans_checked == 0:
        print("::error::No transaction spans found in the workspace. Either `.begin()` "
              "moved or this check's span detection is broken; both are failures.")
        return 1

    if findings:
        for fpath, line, _, desc, where in sorted(set(findings)):
            print(f"::error file={fpath},line={line}::Pool access {where}: {desc}")
        print()
        print("Transaction/pool check failed.")
        print()
        print("SQLite runs with max_connections(1) (crates/trakkt-core/src/db.rs), so an")
        print("open transaction holds the only connection. A pool call before the commit")
        print("waits on a connection the transaction cannot release, stalls for sqlx's")
        print("30s acquire_timeout and then fails with PoolTimedOut.")
        print()
        print("Fixes, in order of preference:")
        print("  * use the transaction: tx_execute!/tx_fetch_*!/tx_with! take &mut DbTx")
        print("    and mirror the db_* macros one for one;")
        print("  * add a `_tx` variant of the helper that takes &mut DbTx;")
        print("  * move the work before db.begin() (authorization reads, validation) or")
        print("    after the commit (broadcasts, notifications).")
        print()
        print("See docs/CODING_STANDARDS.md '### Transactions' and the header of")
        print("scripts/check-tx-pool.py, which also lists what this check cannot see.")
        return 1

    print(
        f"✅ No pool access inside an open transaction: {spans_checked} transaction "
        f"spans and {tx_fns_checked} `&mut DbTx` helper bodies checked against "
        f"{len(pool_macros)} pool-scoped macros "
        f"({', '.join(m + '!' for m in pool_macros)}) and "
        f"{sum(len(v) for v in pool_fns.values())} `&DbPool`-taking functions."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
