#!/usr/bin/env bash
# wasm-test-isolated.sh — runs the trakkt-ui wasm suite one module at a time.
#
# Why this exists: `any_spawner`'s executor is process-global and initialized
# once per test binary. A test that constructs an `Effect`, `Resource` or
# `LocalResource` before calling `mount_to` spawns onto it directly — `mount_to`
# is what initializes it in production — so such a test passes only if some
# earlier test in the same binary already initialized the executor. That is an
# ordering dependency between tests, and a runner that executes the whole binary
# once, in one order, is structurally incapable of seeing it.
#
# It has bitten twice. Before PR #285 exactly one private helper in
# cache/sync_engine.rs initialized the executor, and every other spawning test in
# the crate silently depended on one of its two callers running first. The full
# suite was green in CI and locally the entire time. PR #285 added four spawning
# tests, CI's ordering stopped cooperating, and four tests failed with:
#
#     tried to spawn a Future with Executor::spawn_local() before a global
#     executor was initialized.
#
# The only thing that found it was running one module on its own. This script is
# that, automated: N filtered runs, each a fresh binary instance in a fresh
# browser, so a test that needs a neighbour to have run first has no neighbour.
#
# Run it locally exactly as CI runs it:  scripts/wasm-test-isolated.sh
#
# Per-module rather than per-test: per-test would be the strongest possible
# check, but it is 74 browser launches instead of 13 for a class of dependency
# that has so far always crossed a module boundary. Per-module is the point on
# that curve this repo pays for; see the wasm-test job in ci.yml for the numbers.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# wasm-pack resolves the crate path below relative to the working directory, and
# picks up Cargo.toml and the lockfile from it. CI happens to invoke this from
# the repository root; moving there explicitly is what makes `scripts/…` and
# `../scripts/…` and an absolute path all mean the same run.
cd "$REPO_ROOT"

CRATE_DIR="crates/trakkt-ui"
SRC_DIR="$REPO_ROOT/$CRATE_DIR/src"

# Identical to the arguments the `wasm-test` job in .github/workflows/ci.yml
# used before this script replaced them, so the sweep and the whole-binary run it
# subsumes exercise the same build. `--locked` included: in CI the lockfile has
# just been regenerated by the "Strip local dev patches" steps, and validating
# against it is what proves those steps produced a resolvable graph.
WASM_PACK_ARGS=(test --headless --firefox "$CRATE_DIR" --lib --features hydrate --locked)

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

failed=0

fail() {
    echo "::error::$1"
    failed=1
}

# Parses the harness summary line, which wasm-bindgen-test writes as:
#   test result: ok. 74 passed; 0 failed; 0 ignored; 0 filtered out; finished in 8.69s
# Echoes "<passed> <failed> <ignored> <filtered>". Empty output means the line was
# absent — the harness never reported, which is a failure to be surfaced and never
# to be read as zeroes.
parse_summary() {
    sed -n 's/^test result: [^.]*\. \([0-9]*\) passed; \([0-9]*\) failed; \([0-9]*\) ignored; \([0-9]*\) filtered out.*/\1 \2 \3 \4/p' "$1"
}

# ---------------------------------------------------------------------------
# 1. Enumerate the tests the binary actually contains.
#
# `--list` is the authority on test names because it is the same string the
# runner's FILTER argument is matched against. It compiles the test binary but
# launches no browser (~2.5s once the build is warm), so every consistency check
# below runs before a single browser launch is paid for.
#
# Only `: test` entries are taken. The harness also lists `: bench` entries,
# which a plain run does not execute — counting them would make the totals
# disagree for a reason that has nothing to do with ordering.
# ---------------------------------------------------------------------------
echo "==> Listing wasm tests in $CRATE_DIR"
if ! wasm-pack "${WASM_PACK_ARGS[@]}" -- --list >"$WORK_DIR/list.raw" 2>&1; then
    cat "$WORK_DIR/list.raw"
    echo "::error::Could not list the wasm tests — the build above failed."
    exit 1
fi

sed -n 's/^\([A-Za-z_][A-Za-z0-9_:]*\): test$/\1/p' "$WORK_DIR/list.raw" | LC_ALL=C sort >"$WORK_DIR/all_tests"
total_listed="$(wc -l <"$WORK_DIR/all_tests" | tr -d ' ')"

if [ "$total_listed" -eq 0 ]; then
    cat "$WORK_DIR/list.raw"
    echo "::error::No wasm tests found. This check cannot guard a suite it can't see."
    exit 1
fi
echo "    $total_listed tests"

# ---------------------------------------------------------------------------
# 2. Derive the module list from the source tree.
#
# Derived, never hand-written. A hard-coded list reintroduces the defect one
# level up: this check exists because a test could silently skip an obligation,
# and a list someone has to remember to edit lets a whole module silently skip
# the check. The ticket that prompted this named nine modules; there were
# thirteen by the time it was implemented, days later.
#
# A file's tests are all named `<file's module path>::…`, whatever the inner
# `mod` is called — and the inner names do vary here (`wasm_tests`,
# `latency_tests`, `row_owned_save_probe`, `view_tab_rebuild_tests`). So the file
# path mapped to its module path is the filter, e.g.
# `src/cache/apply.rs` -> `cache::apply`, `src/cache/mod.rs` -> `cache`.
#
# The full module path rather than the bare file stem (`apply`): the runner's
# FILTER is a substring match, so a stem can collide with an unrelated module and
# silently over- or under-select. Step 3 proves the paths chosen here do neither.
#
# Matched at the start of a line so a mention of the attribute inside a doc
# comment or a string is not read as a test. A file this misses is not silently
# dropped — its tests then belong to no module and step 3 fails.
# ---------------------------------------------------------------------------
modules=()
while IFS= read -r file; do
    rel="${file#"$SRC_DIR"/}"     # cache/apply.rs
    rel="${rel%.rs}"              # cache/apply
    rel="${rel%/mod}"             # a mod.rs names the directory's module

    # src/lib.rs is the crate root: its tests carry no module prefix at all, so
    # no filter can select them without also selecting every other test. There is
    # no correct filter to derive, and guessing one would under-report.
    if [ "$rel" = "lib" ]; then
        fail "Wasm tests live in $CRATE_DIR/src/lib.rs. Crate-root tests have no module prefix to filter on and cannot be isolated — move them into a module."
        continue
    fi

    modules+=("${rel//\//::}")
done < <(grep -rlE '^[[:space:]]*#\[wasm_bindgen_test' --include='*.rs' "$SRC_DIR" | LC_ALL=C sort)

# Exits rather than accumulating: there is nothing left to check, and expanding
# an empty array under `set -u` is itself an error on bash before 4.4, which would
# replace this message with an "unbound variable" that explains nothing.
if [ "${#modules[@]}" -eq 0 ]; then
    echo "::error::No source file under $CRATE_DIR/src declares a #[wasm_bindgen_test], yet $total_listed tests were listed. The derivation is broken."
    exit 1
fi

# ---------------------------------------------------------------------------
# 3. Prove the derived filters partition the suite, before running anything.
#
# Two failure modes, both of which would otherwise leave the sweep passing
# vacuously while covering less than it claims:
#   - a filter matching no test — the derivation drifted, or a file was renamed;
#   - a test matched by no filter, or by two.
#
# Checked set-wise rather than by comparing counts: one module under-selecting
# while another over-selects can leave the totals equal, and a sweep that
# balances two opposite mistakes is not a sweep that covered the suite.
#
# `grep -F` is used because the filter is matched as a literal substring here for
# exactly the reason the runner matches it as one — this must model the runner's
# selection, not improve on it.
# ---------------------------------------------------------------------------
: >"$WORK_DIR/claims"          # <module>\t<test name>, one per selection

# Indexed and parallel to `modules` rather than an associative array, which bash
# only grew in 4.0 — the bash macOS ships as /bin/bash is still 3.2, and this
# script is meant to be runnable wherever Firefox and wasm-pack are. Appended
# before the zero check below so the two arrays cannot drift out of step.
expected_count=()

for module in "${modules[@]}"; do
    matched="$(grep -F "$module" "$WORK_DIR/all_tests" || true)"
    count="$(printf '%s' "$matched" | grep -c . || true)"
    expected_count+=("$count")

    if [ "$count" -eq 0 ]; then
        fail "Module filter '$module' matches none of the $total_listed tests. Either the file/module-path mapping is wrong, or that file is not reachable from the crate's module tree and its tests are never compiled."
        continue
    fi

    while IFS= read -r name; do
        printf '%s\t%s\n' "$module" "$name" >>"$WORK_DIR/claims"
    done <<<"$matched"
done

cut -f2 "$WORK_DIR/claims" | LC_ALL=C sort >"$WORK_DIR/claimed"

# A test claimed twice means two filters overlap, so the sweep would run it in
# neither isolation — both runs carry the other module along.
while IFS= read -r name; do
    [ -n "$name" ] || continue
    claimants="$(awk -F'\t' -v n="$name" '$2 == n { printf "%s ", $1 }' "$WORK_DIR/claims")"
    fail "Test '$name' is selected by more than one module filter (${claimants% }). These filters overlap, so neither module is run in isolation."
done < <(LC_ALL=C uniq -d "$WORK_DIR/claimed")

# A test claimed by nobody is a test this check never runs in isolation, which is
# precisely the hole the check exists to close.
while IFS= read -r name; do
    [ -n "$name" ] || continue
    fail "Test '$name' is selected by no module filter, so the isolated sweep would never run it. Its source file was not recognised as declaring wasm tests."
done < <(LC_ALL=C comm -23 "$WORK_DIR/all_tests" <(LC_ALL=C uniq "$WORK_DIR/claimed"))

if [ "$failed" -ne 0 ]; then
    echo ""
    echo "The derived module list does not cover the wasm suite exactly. Fix the"
    echo "derivation in scripts/wasm-test-isolated.sh before trusting a green sweep."
    exit 1
fi

echo "==> ${#modules[@]} modules cover all $total_listed tests exactly"

# ---------------------------------------------------------------------------
# 4. The whole-binary run.
#
# This is what CI ran before this script existed, kept because it is the only run
# that exercises the suite in the order a developer sees locally, and because its
# executed total is the number every per-module run is reconciled against. Taking
# that number from `--list` alone would only prove the sweep is self-consistent.
# ---------------------------------------------------------------------------
echo ""
echo "==> Whole-binary run (all $total_listed tests)"
if ! wasm-pack "${WASM_PACK_ARGS[@]}" >"$WORK_DIR/full.log" 2>&1; then
    cat "$WORK_DIR/full.log"
    fail "The whole-binary wasm run failed. Fix that before reading the isolated results below — an ordering bug is not the likely explanation when the suite fails in its usual order too."
fi

read -r full_passed full_failed full_ignored full_filtered <<<"$(parse_summary "$WORK_DIR/full.log")"
if [ -z "${full_passed:-}" ]; then
    cat "$WORK_DIR/full.log"
    echo "::error::The whole-binary run printed no 'test result:' line — the harness never reported."
    exit 1
fi

total_executed=$((full_passed + full_failed + full_ignored))
echo "    $full_passed passed; $full_failed failed; $full_ignored ignored; $full_filtered filtered out"

if [ "$total_executed" -ne "$total_listed" ]; then
    fail "The whole-binary run executed $total_executed tests but the binary lists $total_listed. The sweep is reconciled against the executed total, so it cannot be trusted while these disagree."
fi

# ---------------------------------------------------------------------------
# 5. The sweep: one filtered run per module, each a fresh binary in a fresh
#    browser. Every module is run even after one fails — each browser launch
#    costs ~9s and reporting all the ordering dependencies at once beats
#    rediscovering them one push at a time.
# ---------------------------------------------------------------------------
echo ""
echo "==> Isolated runs (${#modules[@]} modules)"
swept=0

for i in "${!modules[@]}"; do
    module="${modules[$i]}"
    expected="${expected_count[$i]}"
    log="$WORK_DIR/module.log"
    run_status=0
    wasm-pack "${WASM_PACK_ARGS[@]}" -- "$module" >"$log" 2>&1 || run_status=$?

    read -r passed run_failed ignored filtered <<<"$(parse_summary "$log")"
    if [ -z "${passed:-}" ]; then
        cat "$log"
        fail "$module: the harness printed no 'test result:' line (wasm-pack exited $run_status). Treating that as zero tests would hide the whole module."
        continue
    fi

    selected=$((passed + run_failed + ignored))
    swept=$((swept + selected))
    printf '    %-45s %2d selected, %2d passed, %2d failed\n' "$module" "$selected" "$passed" "$run_failed"

    if [ "$run_failed" -ne 0 ]; then
        # The full output, not just the count: when this fires the interesting
        # part is the panic message, and "before a global executor was
        # initialized" is the signature this whole script is built around.
        cat "$log"
        fail "$module: $run_failed test(s) fail when the module runs on its own but the whole binary is green. That is an ordering dependency — the module needs whatever an earlier test was doing for it (for the executor, an explicit Executor::init_* in the test itself)."
    fi

    if [ "$selected" -ne "$expected" ]; then
        fail "$module: ran $selected tests, but the filter matched $expected at list time. The binary changed underneath this run."
    fi

    if [ $((selected + filtered)) -ne "$total_listed" ]; then
        fail "$module: $selected selected + $filtered filtered out = $((selected + filtered)), not $total_listed. This run saw a different binary than the whole-binary run did."
    fi
done

# ---------------------------------------------------------------------------
# 6. The sweep covered the suite.
#
# Reconciled against the executed total rather than the listed one so this asserts
# what actually ran, in both directions: a module quietly dropped from the sweep
# lands short, an overlap lands over.
# ---------------------------------------------------------------------------
echo ""
if [ "$swept" -ne "$total_executed" ]; then
    fail "The isolated runs executed $swept tests in total; the whole-binary run executed $total_executed. The sweep did not cover the suite."
fi

if [ "$failed" -ne 0 ]; then
    echo ""
    echo "Isolated wasm test sweep failed. A test that passes in the whole binary but"
    echo "fails on its own depends on another test having run first — see the comment"
    echo "at the top of scripts/wasm-test-isolated.sh for why that keeps happening."
    exit 1
fi

echo "✅ All $total_executed wasm tests pass with their module run in isolation (${#modules[@]} modules, plus the whole binary)."
